version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
      - "2222:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - admin
    links:
      - "admin:admin"
      - "app:app"
  admin:
    build:
      context: .
      dockerfile: strapi.Dockerfile
    restart: always
    image: ghcr.io/pratovvt/admin:latest
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: database
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
      PORT: 1338
    ports:
      - "1338:3001"
    volumes:
      - ./admin:/admin
    links:
      - "database:database"
    depends_on:
      - database
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: ghcr.io/pratovvt/back:latest
    environment:
      PG_HOST: database
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: postgres
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    links:
      - "database:database"
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    ports:
      - "4444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./.db:/var/lib/postgresql/data
