name: Docker Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest \
            -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{  github.ref_name }} .
          docker login ghcr.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{  github.ref_name }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest